  # YAML Reference http://www.yaml.org/refcard.html


logging:
  level:
    org:
      kinotic: DEBUG

spring:
  devtools:
    livereload:
      port: 35730

elastic:
  hosts: localhost:9200
  useSSL: false
  user:
  password: